name: gee3
on: push

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: auther
        run: |
          eval 'set +o history' 2>/dev/null || setopt HIST_IGNORE_SPACE 2>/dev/null
          touch ~/.gitcookies
          chmod 0600 ~/.gitcookies
          git config --global http.cookiefile ~/.gitcookies
          tr , \\t <<\__END__ >>~/.gitcookies
          ${{secrets.EECRED}}
          __END__
          eval 'set -o history' 2>/dev/null || unsetopt HIST_IGNORE_SPACE 2>/dev/null
      - name: commit files
        run: |
          git clone https://earthengine.googlesource.com/users/sat-io/default
          cd default
          rm -r .git
          ls -l -a
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated datasets ${today}" -a
      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
